We don't currently use flake8
pytest-flake8 is causing CI to fail with Python 3.12 with

pluggy._manager.PluginValidationError: Plugin 'flake8' for hook 'pytest_collect_file'
hookimpl definition: pytest_collect_file(file_path, path, parent)
Argument(s) {'path'} are declared in the hookimpl but can not be found in the hookspec

Since we don't use flake8, just remove this.